#datasource:
#     username: root
#     password: root
#     url: jdbc:mysql://localhost:3306/hotel?serverTimezone=GMT%2B8
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo

